#SPDX-License-Identifier: MIT-0
---
- name: Install apache httpd (state=present is optional)
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes

- name: Copy File
  ansible.builtin.copy:
    src: /home/prayag/ansible_quickstart/httpd/files/inventory.ini
    dest: /var/www/html/

